### ISSUE TITLE
Person/People generator

### ISSUE THREAD

**Issue by JustinPhlegar** [Orasi/Selenium-Java-Core#52]
A way to generate random information about a person will be a helpful tool. I have something similar built at disney, but relies on an API call. I've been bitten as that API may not be up at the time of the test run, so a way to seed the data ourselves would be more beneficial.

**Comment by simpkinscm** [comment]
Can you provide an example of the information it would need to returned? (Just names, names and address, etc)

**Comment by JustinPhlegar** [comment]
Attached are the classes I made for Disney. Looking to recreate or just reuse this as much as possible. There is a separate class for Email, Address and Phone so they can work independently. The Guest (Person) class has it's own data along with an array of Email, Address, and Phone as a person can have multiples of each. HouseHold (People) is just a collection of Guests, along with some metadata such as how many guests are adults, ad how many are children. So information may not be necessary, the People class may not be necessary either, but it provides a simple way of creating multiples at one time as you pass in an int of how many people to create when instantiating HouseHold. Again, a lot of the functionality in this classes may not be necessary as some data are disney specific. But the way it is set up, all data is iteratable, making coding simple and efficient.


[HouseHold.zip](https://github.com/Orasi/Selenium-Java-Core/files/73306/HouseHold.zip)

**Comment by simpkinscm** [comment]
I through together a quick class that might work for generating people and information.
[Customer.txt](https://github.com/Orasi/Selenium-Java-Core/files/75645/Customer.txt)

**Comment by JustinPhlegar** [comment]
Created with c0dddd38a1711afd2c6c89d23513f71bdd10824b
