### ISSUE TITLE
Alert Handler - add the authentication methods

### ISSUE THREAD

**Issue by jessicamarshall** [Orasi/Selenium-Java-Core#85]
The selenium alert class has authentication methods for alert authentication dialog.  If we have an alert handler class, then this functionality should be included.  

Alert alert = null;
Credentials user = new UserAndPassword(username, password)
alert.authenticateUsing(user);

**Comment by JustinPhlegar** [comment]
Would this be favorable? 
```
public static void handleAlert(WebDriver driver, int timeout, Credentials user){
      if(isAlertPresent(driver, timeout)) alertHandler(driver, user);
}
```
```
private static void alertHandler(WebDriver driver, Credentials user){
	try {
            Alert alert = driver.switchTo().alert()
            TestReporter.log("Closing alert popup with text [ <i>" + alert.getText() +" </i> ] <br />");
            alert.authenticateUsing(user);            	        
      } catch (Exception e) 
      	        //exception handling
      }
}
```

**Comment by jessicamarshall** [comment]
Looks great!  Just what it needs

**Comment by jessicamarshall** [comment]
I would actually think having the alert handler class use the Credentials class - so the user doesn't have to pull that in.  Thoughts?

	public static void handleAlert(WebDriver driver, int timeout, String username, String password){
		Credentials user = new UserAndPassword(username, password);
		if(isAlertPresent(driver, timeout)) alertHandler(driver, user);
	}

**Comment by JustinPhlegar** [comment]
Then we get the scenario of is the User/Pass encoded or not. Then we would need a separate method for plain text credentials and one for encoded credentials. By passing in the Creds class, the user has already handled this and we don't have to worry about it.

**Comment by jessicamarshall** [comment]
Great point - agreed!

**Comment by JustinPhlegar** [comment]
Landed in Stage. Closing issue.
